server: 
  port: 9527
 
spring: 
  application:
    name: read-zuul-gateway
    
zuul: 
  prefix: /yong
  ignored-services: "*"
  routes: 
    myread.serviceId: read-user-provider8001
    myread.path: /myread/**
 #http://myzuul.com:9527/yong/myread/readUser/get/1
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
info:
  app.name: yong-read-P
  company.name: www.yong.com
  build.artifactId: read-gateway
  build.version: 0.0.1-SNAPSHOT