server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.yong.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
    
spring:
   application:
    name: read-user-provider8001 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/readcloudDB01?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: read-user-provider8001
  prefer-ip-address: true
  
info:
  app.name: yong-read-P
  company.name: www.yong.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$