server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
 
spring:
  application:
    name: sr-manage-consumer
  thymeleaf:
   prefix: classpath:/templates/
   suffix: .html
   mode: HTML5
   encoding: UTF-8
   cache: false